name: CI

on:
  workflow_call:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions: {}

jobs:
  check:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@fbc6f3992d24b796d5a048ff273f7fcc4a7b6c09
        with:
          persist-credentials: false

      - uses: jdx/mise-action@c2a87611a18de5b3828c5652fe268e992400cb5c
        with:
          cache: true

      - name: Install
        run: mise run install

      - name: Lint & format
        run: mise run format check

      - name: Typecheck
        run: mise run typecheck

      - name: Test on Python 3.10 - 3.13
        run: mise run test matrix
